class Exception {

}

class Exception2 {

}

var x: num = 1;
try{
	x = 2;
}
catch(e: Exception) {
	x = 3;
}
catch(e: Exception2) {
	x = 4;
}
finally {
	x = 5;
}

print(x);
